#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'vilige-zhang','console_scripts','zhang3'
__requires__ = 'vilige-zhang'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('vilige-zhang', 'console_scripts', 'zhang3')()
    )
