<robot name="my_car_move" xmlns:xacro="http://ros.org/wiki/xacro"> 

    <!-- 控制器 -->
    <gazebo>
        <plugin name='diff_drive' filename='libgazebo_ros_diff_drive.so'>
            <!-- <ros>
                    <namespace>/fishbot</namespace>
                    <remapping>cmd_vel:=cmd_vel</remapping>
                    <remapping>odom:=odom</remapping>
                </ros> -->
            <!-- wheels -->
            <left_joint>left2link</left_joint>
            <right_joint>right2link</right_joint>
            <!-- 车轮间距 -->
            <wheel_separation>${base_width * 2}</wheel_separation> <!-- 车轮间距 -->
            <!-- 车轮直径 -->
            <wheel_diameter>${main_wheel_radius * 2}</wheel_diameter><!-- 车轮直径 -->
            <!-- limits -->
            <max_wheel_torque>20</max_wheel_torque>
            <max_wheel_acceleration>0.5</max_wheel_acceleration>
            <!-- output -->
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>
            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_footprint</robot_base_frame>
        </plugin>

        <plugin name="car_joint_state" filename="libgazebo_ros_joint_state_publisher.so">
            <ros>
                <remapping>~/out:=joint_states</remapping>
            </ros>
            <update_rate>30</update_rate>
            <joint_name>left2link</joint_name>
            <joint_name>right2link</joint_name>
            <!-- <joint_name>caster_joint</joint_name> -->
        </plugin>


    </gazebo>

</robot>
