<?xml version="1.0"?>
<robot name="mycar" xmlns:xacro="http://ros.org/wiki/xacro">    
    <!-- 雷达相关参数 -->
    <xacro:property name="laser_length" value="0.02" />
    <xacro:property name="laser_radius" value="0.02" />
    <xacro:property name="laser_m" value="0.01" />
    
    <!-- 雷达宏实现 -->
    <xacro:macro name="add_laser" params="name type">
        <link name="laser_link${name}">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder length="${laser_length}" radius="${laser_radius}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <!-- 碰撞检测设置 -->
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder length="${laser_length}" radius="${laser_radius}"/>
                </geometry>
            </collision>
            <!-- 惯性矩阵设置 -->
            <xacro:cylinder_inertial_matrix m="${laser_m}" r="${laser_radius}" h="${laser_length}" />

        </link>

        <joint name="laser_joint${name}" type="fixed">
            <parent link="base_link" />
            <child link="laser_link${name}" />


            <xacro:if value="${type == 'left'}">
                <origin xyz="${base_length/2} ${base_width/2} ${base_depth/2}" />
            </xacro:if>
            <xacro:if value="${type == 'right'}">
                <origin xyz="${-base_length/2} ${-base_width/2} ${base_depth/2}" />
            </xacro:if>

            
            <!-- 设置关节旋转 -->
            <axis xyz="0 0 0" />
        </joint>

    </xacro:macro>

    <!-- 调用宏添加雷达 -->
    <xacro:add_laser name="1" type="left"/>
    <xacro:add_laser name="2" type="right"/>

    <gazebo reference="laser_link1">
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="laser_link2">
        <material>Gazebo/Black</material>
    </gazebo>

</robot>
